# Generated by Django 3.1 on 2021-04-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaterialName', models.CharField(max_length=30)),
                ('maker', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('ChemName', models.CharField(max_length=200)),
                ('TechInfo', models.CharField(max_length=1000)),
            ],
        ),
    ]
